DROP TABLE IF EXISTS `user`;

CREATE TABLE `user`
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	dept_id BIGINT(20) NOT NULL COMMENT '部门ID',
	user_name VARCHAR(30) NULL DEFAULT NULL COMMENT '名称',
	age INT(3) NULL DEFAULT NULL COMMENT '年龄',
	money DECIMAL (13,3) NULL DEFAULT NULL COMMENT 'DECIMAL',
	role INT(2) NULL DEFAULT NULL COMMENT '测试',
	phone VARCHAR(13) NULL DEFAULT NULL COMMENT '手机号码',
	create_time DATETIME NULL DEFAULT NULL COMMENT '日期',
	PRIMARY KEY (id)
);